server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: password
  jpa:
    hibernate:
#     only for dev purposes
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#    show-sql: true

#  Custom paths for docs
#  /api-docs
#  /swagger-ui
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui