server:
  error:
    include-message: always

spring:
  datasource:
#   this shouldn't be visible :)
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: password
  jpa:
    hibernate:
#     only for dev purposes
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

web:
  filter:
    cors:
      allowed-headers: Origin,Content-Type,Accept,Authorization
      allowed-methods: GET,POST,PUT,PATCH,DELETE,ORIGIN
      allowed-origins: "http://localhost:5173"
  security:
#   this shouldn't be visible :)
    jwtSecret: ===================================================aSecretThatShouldntBeRevealed===================================================
    jwtExpirationMs: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

initializer:
  user:
    username: piotrd
    email: piotr.damrych@icloud.com
    password: password