version: "3.8"

services:
  postgres:
    container_name: postgresmarketplace
    build: ./postgres
    # they shouldn't be visible :)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgresmarketplace
    volumes:
      - postgres:/data/postgresmarketplace
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: